# Generated by Django 3.1.6 on 2021-02-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210216_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short_urls',
            name='long_url',
            field=models.URLField(max_length=1000, verbose_name='URL'),
        ),
    ]
